export const LIST_FOCUS = 'FOCUS_LIST_FOCUS';
export const SET_CHARTGROUP = 'FOCUS_SET_CHARTGROUP';
export const SHOW_FILTER = 'FOCUS_SHOW_FILTER';
export const HIDE_FILTER = 'FOCUS_HIDE_FILTER';
export const CHANGE_FILTER = 'FOCUS_CHANGE_FILTER';
export const CANCEL_FOCUS = 'FOCUS_CANCEL_FOCUS';
export const IS_SHOW_GUIDE = 'IS_SHOW_GUIDE';
